services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
      
  applyservice:
    build:
      context: .
      dockerfile: ./ApplyService/Dockerfile
    ports:
      - "5001:8080"
    depends_on:
      - rabbitmq

  interviewservice:
    build:
      context: .
      dockerfile: ./InterviewService/Dockerfile
    ports:
      - "5002:8080"
    depends_on:
      - rabbitmq
